version: "3.9"
services:
  go-rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
    volumes:
      - .:/code/

  database:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: ssm
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./tmp/db/data:/var/lib/mysql